
server:
  port: 3333
spring:
   datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url:  jdbc:oracle:thin:@localhost:1521:xe
      username: rocky
      password: rocky322
   jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
         dialect:
          hibernate:
             dialect:org.hibernate.dialect.Oracle10gDialect
